language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO="Django==1.4.5"
  - DJANGO="Django==1.5.1"
  - DJANGO="https://www.djangoproject.com/download/1.6b1/tarball/"

install:
  - pip install -q $DJANGO
  - python setup.py -q install
  - pip install -r requirements.txt --use-mirrors

script: django-admin.py test ereports --settings=ereports.tests.settings
